import React, { createContext, useState, useEffect, useContext, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { LANGUAGES } from '../constants/languages';

// Storage key for app language
const APP_LANGUAGE_KEY = 'app_language';

// Default language is English
const DEFAULT_LANGUAGE = 'en';

// Interface for our context
interface LanguageContextType {
  appLanguage: string;
  setAppLanguage: (code: string) => Promise<void>;
  translate: (key: string) => string;
  getLanguageName: (code: string) => string;
}

// Create the context with a default value
const LanguageContext = createContext<LanguageContextType>({
  appLanguage: DEFAULT_LANGUAGE,
  setAppLanguage: async () => {},
  translate: () => '',
  getLanguageName: () => '',
});

// Translations for UI elements
const translations: Record<string, Record<string, string>> = {
  // English translations
  en: {
    // Profile Screen
    'profile.title': 'Confluency',
    'profile.guest': 'Guest',
    'profile.editProfile': 'Edit Profile',
    'profile.settings': 'Settings',
    'profile.appLanguage': 'App Language',
    'profile.subscription': 'Subscription',
    'profile.currentPlan': 'Current Plan',
    'profile.support': 'Support',
    'profile.helpCenter': 'Help Center',
    'profile.contactUs': 'Contact Us',
    'profile.legal': 'Legal',
    'profile.privacyPolicy': 'Privacy Policy',
    'profile.termsOfService': 'Terms of Service',
    'profile.version': 'Version',
    'profile.logoutConfirmTitle': 'Confirm Logout',
    'profile.logoutConfirmMessage': 'Are you sure you want to log out?',
    'profile.logoutError': 'An error occurred during logout. Please try again.',
    
    // Legacy keys (keeping for backward compatibility)
    'profile.section.subscription': 'Subscription',
    'profile.manage.subscription': 'Manage Subscription',
    'profile.section.preferences': 'Preferences',
    'profile.app.language': 'App Language',
    'profile.learning.languages': 'Learning Languages',
    'profile.change': 'Change',
    'profile.section.support': 'Support',
    'profile.contact.support': 'Contact Support',
    'profile.section.account': 'Account',
    'profile.logout': 'Log Out',
    'profile.logout.confirm.title': 'Confirm Logout',
    'profile.logout.confirm.message': 'Are you sure you want to log out?',
    'profile.logout.confirm.cancel': 'Cancel',
    'profile.logout.confirm.logout': 'Log Out',

    // Subscription Screen
    'subscription.title': 'Confluency Tokens',
    'subscription.current': 'Current Subscription',
    'subscription.plan': 'Plan',
    'subscription.usage': 'Confluency Tokens Usage',
    'subscription.reset': 'Resets on',
    'subscription.available.plans': 'Available Plans',
    'subscription.restore': 'Restore Purchases',
    'subscription.expo.notice': 'Running in development mode. Purchases are simulated and not charged.',
    'subscription.legal.text': 'Subscriptions will automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period.',
    'subscription.manage.text': 'You can manage your subscriptions in your App Store/Google Play account settings after purchase.',
    
    // Language Selection
    'language.i.speak': 'I speak:',
    'language.want.to.learn': 'I want to learn:',
    'language.difficulty': 'Difficulty:',
    'language.conversation.mode': 'Conversation Mode:',
    'language.learning.objective': 'Learning Objective (optional):',
    'language.start.button': 'Start Learning',
    'language.app.title': 'App Language',

    // Conversation Mode Translations
    'conversation.categories.conversations': 'Conversations',
    'conversation.categories.languageLessons': 'Language Lessons',
    'conversation.freeConversation.label': 'Free Conversation',
    'conversation.freeConversation.description': 'Engage in natural, unstructured conversations about any topic that interests you.',
    'conversation.freeConversation.placeholder': '• Game of Thrones\n• Golfing Tips\n• Holiday Destinations',
    'conversation.topicLesson.label': 'Special Topic Lesson',
    'conversation.topicLesson.description': 'Explore fascinating topics in your target language - history, culture, sport, geopolitics...',
    'conversation.topicLesson.placeholder': '• History of Rome\n• Dog Training Tips\n• Modern Art Movements',
    'conversation.interview.label': 'Interview',
    'conversation.interview.description': 'Express yourself naturally while answering questions about your interests, experiences and opinions.',
    'conversation.interview.placeholder': '• Your Hobbies\n• Travel Experiences\n• Life Goals',
    'conversation.situationSimulation.label': 'Situation Simulation',
    'conversation.situationSimulation.description': 'Practice real-life conversations in common scenarios like restaurants, travel, and shopping.',
    'conversation.situationSimulation.placeholder': '• At a restaurant\n• Job interview\n• Airport check-in\n• Shopping for clothes',
    'conversation.verbChallenge.label': 'Verb Challenge',
    'conversation.verbChallenge.description': 'Practice constructing sentences with essential verbs in different tenses and moods.',
    'conversation.verbChallenge.placeholder': '• Specific verb tenses to practice\n• Difficulty level preferences\n• Types of verbs',
    'conversation.verbChallenge.comingSoon': 'Coming Soon',
    'conversation.topicTheme.label': 'Topic/Theme',
    'conversation.generateRandomTopic': 'Generate Random Topic',
    'conversation.selectMode': 'Select Conversation Mode',
    'conversation.topicInfo': 'Confluency can talk with you about any topic you can dream of - from dating advice to dancing, from Ancient Egypt to Taylor Swift!',
    'loading.generating': 'Generating...',

    // Email Verification
    'email.verification.title': 'Email Verification Required',
    'email.verification.message': 'Your email address needs to be verified before you can continue. Please check your inbox (including spam folder) for a verification email, or use the "Resend Email" button below.',
    'email.verification.ok': 'OK',
    'email.verification.resendEmail': 'Resend Email',
    'email.verification.checkingVerification': 'Checking verification...',
    'email.verification.emailSent': 'Email Sent',
    'email.verification.emailSentMessage': 'A new verification email has been sent. Please check your inbox.',
    'email.verification.errorSending': 'Error Sending',
    'email.verification.errorSendingMessage': 'Failed to send verification email. Please try again.',
    'email.verification.verificationComplete': 'Verification Complete',
    'email.verification.verificationCompleteMessage': 'Your email has been successfully verified.',
    'email.verification.networkError': 'Connection Error',
    'email.verification.networkErrorMessage': 'Please check your internet connection and try again.',
    'email.verification.notVerified': 'Your email is not verified yet. Please check your inbox and click the verification link.',
    'email.verification.checkEmail': 'Please check your email and click the verification link to activate your account.',
    'email.verification.checkEmailTitle': 'Check Your Email',
    'email.verification.checkEmailMessage': 'Please check your email inbox and click the verification link to activate your account. After verification, you\'ll be automatically signed in.',
    'email.verification.cannotOpenEmail': 'Cannot Open Email',
    'email.verification.cannotOpenEmailMessage': 'Unable to open your email app. Please check your email inbox manually.',
    'email.verification.verifyTitle': 'Verify Your Email',
    'email.verification.sentTo': 'We\'ve sent a verification email to:',
    'email.verification.instructions': 'Please check your inbox and click the verification link to activate your account. Don\'t forget to check your spam or junk folder.',
    'email.verification.offlineWarning': 'You are offline. Please connect to the internet to verify your email.',
    'email.verification.openEmailApp': 'Open Email App',
    'email.verification.verifiedButton': 'I\'ve Verified My Email',
    'email.verification.helpText': 'Having trouble? Check your spam folder or contact our support team for assistance.',

    // Quota Exceeded Modal
    'quota.exceeded.title': 'Token Limit Reached',
    'quota.exceeded.message': 'You\'ve reached your monthly token limit for language learning. Upgrade your subscription to continue learning without limits.',
    'quota.exceeded.upgradeNow': 'Upgrade Now',
    'quota.exceeded.notNow': 'Not Now',

    // Loading States
    'loading.general': 'Loading...',
    'loading.savingPreferences': 'Saving preferences...',
    'loading.connecting': 'Connecting...',
    'loading.verifying': 'Verifying...',
    'loading.sendingEmail': 'Sending email...',

    // Status Messages
    'status.offline': 'Offline',
    'status.connecting': 'Connecting...',
    'status.connected': 'Connected',
    'status.disconnected': 'Disconnected',

    // Error Messages
    'error.network.title': 'Connection Error',
    'error.network.message': 'Could not connect to server. Please check your internet connection.',
    'error.auth.generic': 'Authentication error. Please try again.',
    'error.auth.network': 'Network error during authentication.',
    'error.subscription.failed': 'Subscription processing failed.',
    'error.verification.failed': 'Email verification failed.',

    // Placeholders
    'placeholder.learningObjective': 'e.g. Roman history, Japanese culture...',
    'placeholder.searchLanguages': 'Search languages...',
    'placeholder.email': 'your@email.com',
    'placeholder.password': 'Password',

    // Accessibility Labels
    'accessibility.closeModal': 'Close modal',
    'accessibility.selectLanguage': 'Select language',
    'accessibility.backButton': 'Back button',
    'accessibility.menuButton': 'Menu button',

    // Additional Button Labels
    'button.upgradeNow': 'Upgrade Now',
    'button.notNow': 'Not Now',
    'button.resendEmail': 'Resend Email',
    'button.tryAgain': 'Try Again',
    'button.ok': 'OK',

    // Common
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    
    // Buttons
    'button.cancel': 'Cancel',
    'button.save': 'Save',
    'button.select': 'Select',
    'button.continue': 'Continue',
    'button.back': 'Back',
  },
  
  // Spanish translations
  es: {
    'profile.title': 'Confluency',
    'profile.guest': 'Invitado',
    'profile.editProfile': 'Editar Perfil',
    'profile.settings': 'Configuración',
    'profile.appLanguage': 'Idioma de la App',
    'profile.subscription': 'Suscripción',
    'profile.currentPlan': 'Plan Actual',
    'profile.support': 'Soporte',
    'profile.helpCenter': 'Centro de Ayuda',
    'profile.contactUs': 'Contáctanos',
    'profile.legal': 'Legal',
    'profile.privacyPolicy': 'Política de Privacidad',
    'profile.termsOfService': 'Términos de Servicio',
    'profile.version': 'Versión',
    'profile.logoutConfirmTitle': 'Confirmar Cierre de Sesión',
    'profile.logoutConfirmMessage': '¿Estás seguro de que deseas cerrar sesión?',
    'profile.logoutError': 'Ocurrió un error durante el cierre de sesión. Por favor, inténtalo de nuevo.',
    
    // Legacy keys
    'profile.section.subscription': 'Suscripción',
    'profile.manage.subscription': 'Administrar Suscripción',
    'profile.section.preferences': 'Preferencias',
    'profile.app.language': 'Idioma de la App',
    'profile.learning.languages': 'Idiomas de Aprendizaje',
    'profile.change': 'Cambiar',
    'profile.section.support': 'Soporte',
    'profile.contact.support': 'Contactar Soporte',
    'profile.section.account': 'Cuenta',
    'profile.logout': 'Cerrar Sesión',
    'profile.logout.confirm.title': 'Confirmar Cierre de Sesión',
    'profile.logout.confirm.message': '¿Estás seguro de que deseas cerrar sesión?',
    'profile.logout.confirm.cancel': 'Cancelar',
    'profile.logout.confirm.logout': 'Cerrar Sesión',

    'subscription.title': 'Tokens de Confluency',
    'subscription.current': 'Suscripción Actual',
    'subscription.plan': 'Plan',
    'subscription.usage': 'Uso de Tokens de Confluency',
    'subscription.reset': 'Se restablece el',
    'subscription.available.plans': 'Planes Disponibles',
    'subscription.restore': 'Restaurar Compras',
    'subscription.expo.notice': 'Ejecutando en modo de desarrollo. Las compras son simuladas y no se cobran.',
    'subscription.legal.text': 'Las suscripciones se renovarán automáticamente a menos que la renovación automática se desactive al menos 24 horas antes del final del período actual.',
    'subscription.manage.text': 'Puedes administrar tus suscripciones en la configuración de tu cuenta de App Store/Google Play después de la compra.',
    
    'language.i.speak': 'Yo hablo:',
    'language.want.to.learn': 'Quiero aprender:',
    'language.difficulty': 'Dificultad:',
    'language.conversation.mode': 'Modo de Conversación:',
    'language.learning.objective': 'Objetivo de Aprendizaje (opcional):',
    'language.start.button': 'Comenzar a Aprender',
    'language.app.title': 'Idioma de la Aplicación',

    // Conversation Mode Translations
    'conversation.categories.conversations': 'Conversaciones',
    'conversation.categories.languageLessons': 'Lecciones de Idioma',
    'conversation.freeConversation.label': 'Conversación Libre',
    'conversation.freeConversation.description': 'Participa en conversaciones naturales y no estructuradas sobre cualquier tema que te interese.',
    'conversation.freeConversation.placeholder': '• Juego de Tronos\n• Consejos de Golf\n• Destinos de Vacaciones',
    'conversation.topicLesson.label': 'Lección de Tema Especial',
    'conversation.topicLesson.description': 'Explora temas fascinantes en tu idioma objetivo: historia, cultura, deportes, geopolítica...',
    'conversation.topicLesson.placeholder': '• Historia de Roma\n• Consejos de Entrenamiento de Perros\n• Movimientos de Arte Moderno',
    'conversation.interview.label': 'Entrevista',
    'conversation.interview.description': 'Exprésate naturalmente mientras respondes preguntas sobre tus intereses, experiencias y opiniones.',
    'conversation.interview.placeholder': '• Tus Pasatiempos\n• Experiencias de Viaje\n• Objetivos de Vida',
    'conversation.situationSimulation.label': 'Simulación de Situaciones',
    'conversation.situationSimulation.description': 'Practica conversaciones de la vida real en escenarios comunes como restaurantes, viajes y compras.',
    'conversation.situationSimulation.placeholder': '• En un restaurante\n• Entrevista de trabajo\n• Registro en el aeropuerto\n• Compras de ropa',
    'conversation.verbChallenge.label': 'Desafío de Verbos',
    'conversation.verbChallenge.description': 'Practica construyendo oraciones con verbos esenciales en diferentes tiempos y modos.',
    'conversation.verbChallenge.placeholder': '• Tiempos verbales específicos para practicar\n• Preferencias de nivel de dificultad\n• Tipos de verbos',
    'conversation.verbChallenge.comingSoon': 'Próximamente',
    'conversation.topicTheme.label': 'Tema/Asunto',
    'conversation.generateRandomTopic': 'Generar Tema Aleatorio',
    'conversation.selectMode': 'Seleccionar Modo de Conversación',
    'conversation.topicInfo': '¡Confluency puede conversar contigo sobre cualquier tema que puedas imaginar: desde consejos de citas hasta baile, desde el Antiguo Egipto hasta Taylor Swift!',
    'loading.generating': 'Generando...',

    // Email Verification
    'email.verification.title': 'Verificación de Email Requerida',
    'email.verification.message': 'Tu dirección de email debe ser verificada antes de continuar. Por favor revisa tu bandeja de entrada (incluyendo la carpeta de spam) para un email de verificación, o usa el botón "Reenviar Email" abajo.',
    'email.verification.ok': 'OK',
    'email.verification.resendEmail': 'Reenviar Email',
    'email.verification.checkingVerification': 'Verificando...',
    'email.verification.emailSent': 'Email Enviado',
    'email.verification.emailSentMessage': 'Se ha enviado un nuevo email de verificación. Por favor revisa tu bandeja de entrada.',
    'email.verification.errorSending': 'Error al Enviar',
    'email.verification.errorSendingMessage': 'No se pudo enviar el email de verificación. Por favor inténtalo de nuevo.',
    'email.verification.verificationComplete': 'Verificación Completa',
    'email.verification.verificationCompleteMessage': 'Tu email ha sido verificado exitosamente.',
    'email.verification.networkError': 'Error de Conexión',
    'email.verification.networkErrorMessage': 'Por favor verifica tu conexión a internet e inténtalo de nuevo.',
    'email.verification.notVerified': 'Tu email aún no está verificado. Por favor revisa tu bandeja de entrada y haz clic en el enlace de verificación.',
    'email.verification.checkEmail': 'Por favor revisa tu email y haz clic en el enlace de verificación para activar tu cuenta.',
    'email.verification.checkEmailTitle': 'Revisa Tu Email',
    'email.verification.checkEmailMessage': 'Por favor revisa tu bandeja de entrada y haz clic en el enlace de verificación para activar tu cuenta. Después de la verificación, serás conectado automáticamente.',
    'email.verification.cannotOpenEmail': 'No Se Puede Abrir Email',
    'email.verification.cannotOpenEmailMessage': 'No se pudo abrir tu aplicación de email. Por favor revisa tu bandeja de entrada manualmente.',
    'email.verification.verifyTitle': 'Verifica Tu Email',
    'email.verification.sentTo': 'Hemos enviado un email de verificación a:',
    'email.verification.instructions': 'Por favor revisa tu bandeja de entrada y haz clic en el enlace de verificación para activar tu cuenta. No olvides revisar tu carpeta de spam.',
    'email.verification.offlineWarning': 'Estás sin conexión. Por favor conéctate a internet para verificar tu email.',
    'email.verification.openEmailApp': 'Abrir App de Email',
    'email.verification.verifiedButton': 'He Verificado Mi Email',
    'email.verification.helpText': '¿Tienes problemas? Revisa tu carpeta de spam o contacta a nuestro equipo de soporte.',

    // Quota Exceeded Modal
    'quota.exceeded.title': 'Límite de Tokens Alcanzado',
    'quota.exceeded.message': 'Has alcanzado tu límite mensual de tokens para aprendizaje de idiomas. Actualiza tu suscripción para continuar aprendiendo sin límites.',
    'quota.exceeded.upgradeNow': 'Actualizar Ahora',
    'quota.exceeded.notNow': 'Ahora No',

    // Loading States
    'loading.general': 'Cargando...',
    'loading.savingPreferences': 'Guardando preferencias...',
    'loading.connecting': 'Conectando...',
    'loading.verifying': 'Verificando...',
    'loading.sendingEmail': 'Enviando email...',

    // Status Messages
    'status.offline': 'Sin conexión',
    'status.connecting': 'Conectando...',
    'status.connected': 'Conectado',
    'status.disconnected': 'Desconectado',

    // Error Messages
    'error.network.title': 'Error de Conexión',
    'error.network.message': 'No se pudo conectar al servidor. Por favor verifica tu conexión a internet.',
    'error.auth.generic': 'Error de autenticación. Por favor inténtalo de nuevo.',
    'error.auth.network': 'Error de conexión durante la autenticación.',
    'error.subscription.failed': 'Error al procesar la suscripción.',
    'error.verification.failed': 'Error en la verificación del email.',

    // Placeholders
    'placeholder.learningObjective': 'Ej: Historia romana, cultura japonesa...',
    'placeholder.searchLanguages': 'Buscar idiomas...',
    'placeholder.email': 'tu@email.com',
    'placeholder.password': 'Contraseña',

    // Accessibility Labels
    'accessibility.closeModal': 'Cerrar modal',
    'accessibility.selectLanguage': 'Seleccionar idioma',
    'accessibility.backButton': 'Botón de regresar',
    'accessibility.menuButton': 'Botón de menú',

    // Additional Button Labels
    'button.upgradeNow': 'Actualizar Ahora',
    'button.notNow': 'Ahora No',
    'button.resendEmail': 'Reenviar Email',
    'button.tryAgain': 'Intentar de Nuevo',
    'button.ok': 'OK',

    // Common
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.warning': 'Advertencia',
    'common.info': 'Información',
    
    'button.cancel': 'Cancelar',
    'button.save': 'Guardar',
    'button.select': 'Seleccionar',
    'button.continue': 'Continuar',
    'button.back': 'Volver',
  },

  // French translations
  fr: {
    'profile.title': 'Confluency',
    'profile.guest': 'Invité',
    'profile.editProfile': 'Modifier le Profil',
    'profile.settings': 'Paramètres',
    'profile.appLanguage': 'Langue de l\'Application',
    'profile.subscription': 'Abonnement',
    'profile.currentPlan': 'Plan Actuel',
    'profile.support': 'Support',
    'profile.helpCenter': 'Centre d\'Aide',
    'profile.contactUs': 'Nous Contacter',
    'profile.legal': 'Légal',
    'profile.privacyPolicy': 'Politique de Confidentialité',
    'profile.termsOfService': 'Conditions de Service',
    'profile.version': 'Version',
    'profile.logoutConfirmTitle': 'Confirmer la Déconnexion',
    'profile.logoutConfirmMessage': 'Êtes-vous sûr de vouloir vous déconnecter?',
    'profile.logoutError': 'Une erreur s\'est produite lors de la déconnexion. Veuillez réessayer.',
    
    // Legacy keys
    'profile.section.subscription': 'Abonnement',
    'profile.manage.subscription': 'Gérer l\'Abonnement',
    'profile.section.preferences': 'Préférences',
    'profile.app.language': 'Langue de l\'Application',
    'profile.learning.languages': 'Langues d\'Apprentissage',
    'profile.change': 'Modifier',
    'profile.section.support': 'Support',
    'profile.contact.support': 'Contacter le Support',
    'profile.section.account': 'Compte',
    'profile.logout': 'Déconnexion',
    'profile.logout.confirm.title': 'Confirmer la Déconnexion',
    'profile.logout.confirm.message': 'Êtes-vous sûr de vouloir vous déconnecter?',
    'profile.logout.confirm.cancel': 'Annuler',
    'profile.logout.confirm.logout': 'Déconnexion',

    'subscription.title': 'Tokens de Confluency',
    'subscription.current': 'Abonnement Actuel',
    'subscription.plan': 'Plan',
    'subscription.usage': 'Utilisation des Tokens de Confluency',
    'subscription.reset': 'Réinitialisation le',
    'subscription.available.plans': 'Plans Disponibles',
    'subscription.restore': 'Restaurer les Achats',
    'subscription.expo.notice': 'Exécution en mode développement. Les achats sont simulés et non facturés.',
    'subscription.legal.text': 'Les abonnements seront automatiquement renouvelés sauf si le renouvellement automatique est désactivé au moins 24 heures avant la fin de la période en cours.',
    'subscription.manage.text': 'Vous pouvez gérer vos abonnements dans les paramètres de votre compte App Store/Google Play après l\'achat.',
    
    'language.i.speak': 'Je parle:',
    'language.want.to.learn': 'Je veux apprendre:',
    'language.difficulty': 'Difficulté:',
    'language.conversation.mode': 'Mode de Conversation:',
    'language.learning.objective': 'Objectif d\'Apprentissage (optionnel):',
    'language.start.button': 'Commencer l\'Apprentissage',
    'language.app.title': 'Langue de l\'Application',

    // Conversation Mode Translations
    'conversation.categories.conversations': 'Conversations',
    'conversation.categories.languageLessons': 'Leçons de Langue',
    'conversation.freeConversation.label': 'Conversation Libre',
    'conversation.freeConversation.description': 'Engagez-vous dans des conversations naturelles et non structurées sur tout sujet qui vous intéresse.',
    'conversation.freeConversation.placeholder': '• Game of Thrones\n• Conseils de Golf\n• Destinations de Vacances',
    'conversation.topicLesson.label': 'Leçon de Sujet Spécial',
    'conversation.topicLesson.description': 'Explorez des sujets fascinants dans votre langue cible - histoire, culture, sport, géopolitique...',
    'conversation.topicLesson.placeholder': '• Histoire de Rome\n• Conseils de Dressage de Chien\n• Mouvements d\'Art Moderne',
    'conversation.interview.label': 'Entretien',
    'conversation.interview.description': 'Exprimez-vous naturellement en répondant à des questions sur vos intérêts, expériences et opinions.',
    'conversation.interview.placeholder': '• Vos Loisirs\n• Expériences de Voyage\n• Objectifs de Vie',
    'conversation.situationSimulation.label': 'Simulation de Situation',
    'conversation.situationSimulation.description': 'Pratiquez des conversations de la vie réelle dans des scénarios courants comme les restaurants, les voyages et les achats.',
    'conversation.situationSimulation.placeholder': '• Dans un restaurant\n• Entretien d\'embauche\n• Enregistrement à l\'aéroport\n• Achats de vêtements',
    'conversation.verbChallenge.label': 'Défi de Verbes',
    'conversation.verbChallenge.description': 'Pratiquez la construction de phrases avec des verbes essentiels dans différents temps et modes.',
    'conversation.verbChallenge.placeholder': '• Temps verbaux spécifiques à pratiquer\n• Préférences de niveau de difficulté\n• Types de verbes',
    'conversation.verbChallenge.comingSoon': 'Bientôt Disponible',
    'conversation.topicTheme.label': 'Thème/Sujet',
    'conversation.generateRandomTopic': 'Générer un Sujet Aléatoire',
    'conversation.selectMode': 'Sélectionner le Mode de Conversation',
    'conversation.topicInfo': 'Confluency peut converser avec vous sur n\'importe quel sujet que vous pouvez imaginer : des conseils de rencontres à la danse, de l\'Égypte Ancienne à Taylor Swift !',
    'loading.generating': 'Génération...',

    // Email Verification
    'email.verification.title': 'Vérification d\'Email Requise',
    'email.verification.message': 'Votre adresse email doit être vérifiée avant de continuer. Veuillez vérifier votre boîte de réception (y compris le dossier spam) pour un email de vérification, ou utilisez le bouton "Renvoyer l\'Email" ci-dessous.',
    'email.verification.ok': 'OK',
    'email.verification.resendEmail': 'Renvoyer l\'Email',
    'email.verification.checkingVerification': 'Vérification...',
    'email.verification.emailSent': 'Email Envoyé',
    'email.verification.emailSentMessage': 'Un nouvel email de vérification a été envoyé. Veuillez vérifier votre boîte de réception.',
    'email.verification.errorSending': 'Erreur lors de l\'Envoi',
    'email.verification.errorSendingMessage': 'Impossible d\'envoyer l\'email de vérification. Veuillez réessayer.',
    'email.verification.verificationComplete': 'Vérification Terminée',
    'email.verification.verificationCompleteMessage': 'Votre email a été vérifié avec succès.',
    'email.verification.networkError': 'Erreur de Connexion',
    'email.verification.networkErrorMessage': 'Veuillez vérifier votre connexion internet et réessayer.',
    'email.verification.notVerified': 'Votre email n\'est pas encore vérifié. Veuillez vérifier votre boîte de réception et cliquer sur le lien de vérification.',
    'email.verification.checkEmail': 'Veuillez vérifier votre email et cliquer sur le lien de vérification pour activer votre compte.',
    'email.verification.checkEmailTitle': 'Vérifiez Votre Email',
    'email.verification.checkEmailMessage': 'Veuillez vérifier votre boîte de réception et cliquer sur le lien de vérification pour activer votre compte. Après vérification, vous serez connecté automatiquement.',
    'email.verification.cannotOpenEmail': 'Impossible d\'Ouvrir l\'Email',
    'email.verification.cannotOpenEmailMessage': 'Impossible d\'ouvrir votre application email. Veuillez vérifier votre boîte de réception manuellement.',

    // Common
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.loading': 'Chargement...',
    'common.tryAgain': 'Réessayer',
    'common.cancel': 'Annuler',
    'common.ok': 'OK',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.close': 'Fermer',
    'common.done': 'Terminé',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.skip': 'Ignorer',
    'common.required': 'Requis',
    'common.optional': 'Optionnel',
    'common.email': 'Email',
    'common.password': 'Mot de passe',
    'common.confirmPassword': 'Confirmer le mot de passe',
    'common.firstName': 'Prénom',
    'common.lastName': 'Nom de famille',
    'common.name': 'Nom',
    'common.username': 'Nom d\'utilisateur',
    'common.language': 'Langue',
    'common.difficulty': 'Difficulté',
    'common.beginner': 'Débutant',
    'common.intermediate': 'Intermédiaire',
    'common.advanced': 'Avancé',
    'common.save': 'Enregistrer',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.remove': 'Retirer',
    'common.add': 'Ajouter',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.refresh': 'Actualiser',
    'common.retry': 'Réessayer',
    'common.continue': 'Continuer',
    'common.start': 'Commencer',
    'common.stop': 'Arrêter',
    'common.pause': 'Pause',
    'common.play': 'Jouer',
    'common.record': 'Enregistrer',
    'common.send': 'Envoyer',
    'common.receive': 'Recevoir',
    'common.upload': 'Télécharger',
    'common.download': 'Télécharger',
    'common.share': 'Partager',
    'common.copy': 'Copier',
    'common.paste': 'Coller',
    'common.cut': 'Couper',
    'common.undo': 'Annuler',
    'common.redo': 'Refaire',
    'common.settings': 'Paramètres',
    'common.preferences': 'Préférences',
    'common.help': 'Aide',
    'common.about': 'À propos',
    'common.contact': 'Contact',
    'common.support': 'Support',
    'common.feedback': 'Commentaires',
    'common.report': 'Signaler',
    'common.terms': 'Conditions',
    'common.privacy': 'Confidentialité',
    'common.legal': 'Légal',
    'common.version': 'Version',
    'common.update': 'Mettre à jour',
    'common.latest': 'Dernier',
    'common.new': 'Nouveau',
    'common.old': 'Ancien',
    'common.recent': 'Récent',
    'common.popular': 'Populaire',
    'common.featured': 'En vedette',
    'common.recommended': 'Recommandé',
    'common.favorite': 'Favori',
    'common.bookmark': 'Signet',
    'common.like': 'Aimer',
    'common.dislike': 'Ne pas aimer',
    'common.rating': 'Évaluation',
    'common.review': 'Avis',
    'common.comment': 'Commentaire',
    'common.reply': 'Répondre',
    'common.message': 'Message',
    'common.notification': 'Notification',
    'common.alert': 'Alerte',
    'common.warning': 'Avertissement',
    'common.info': 'Information',
    'common.tip': 'Conseil',
    'common.note': 'Note',
    'common.reminder': 'Rappel',
    'common.date': 'Date',
    'common.time': 'Heure',
    'common.today': 'Aujourd\'hui',
    'common.yesterday': 'Hier',
    'common.tomorrow': 'Demain',
    'common.week': 'Semaine',
    'common.month': 'Mois',
    'common.year': 'Année',
    'common.daily': 'Quotidien',
    'common.weekly': 'Hebdomadaire',
    'common.monthly': 'Mensuel',
    'common.yearly': 'Annuel',
    'common.never': 'Jamais',
    'common.always': 'Toujours',
    'common.sometimes': 'Parfois',
    'common.often': 'Souvent',
    'common.rarely': 'Rarement',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.some': 'Certains',
    'common.many': 'Beaucoup',
    'common.few': 'Peu',
    'common.more': 'Plus',
    'common.less': 'Moins',
    'common.most': 'La plupart',
    'common.least': 'Le moins',
    'common.best': 'Meilleur',
    'common.worst': 'Pire',
    'common.better': 'Mieux',
    'common.worse': 'Pire',
    'common.same': 'Même',
    'common.different': 'Différent',
    'common.similar': 'Similaire',
    'common.equal': 'Égal',
    'common.unique': 'Unique',
    'common.special': 'Spécial',
    'common.normal': 'Normal',
    'common.standard': 'Standard',
    'common.custom': 'Personnalisé',
    'common.default': 'Par défaut',
    'common.auto': 'Automatique',
    'common.manual': 'Manuel',
    'common.enabled': 'Activé',
    'common.disabled': 'Désactivé',
    'common.on': 'Activé',
    'common.off': 'Désactivé',
    'common.true': 'Vrai',
    'common.false': 'Faux',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.online': 'En ligne',
    'common.offline': 'Hors ligne',
    'common.connected': 'Connecté',
    'common.disconnected': 'Déconnecté',
    'common.available': 'Disponible',
    'common.unavailable': 'Indisponible',
    'common.busy': 'Occupé',
    'common.free': 'Libre',
    'common.premium': 'Premium',
    'common.pro': 'Pro',
    'common.basic': 'Basique',
    'common.trial': 'Essai',
    'common.demo': 'Démo',
    'common.beta': 'Bêta',
    'common.alpha': 'Alpha',
    'common.stable': 'Stable',
    'common.experimental': 'Expérimental',
    'common.public': 'Public',
    'common.private': 'Privé',
    'common.personal': 'Personnel',
    'common.business': 'Entreprise',
    'common.professional': 'Professionnel',
    'common.student': 'Étudiant',
    'common.teacher': 'Enseignant',
    'common.admin': 'Administrateur',
    'common.user': 'Utilisateur',
    'common.guest': 'Invité',
    'common.member': 'Membre',
    'common.subscriber': 'Abonné',
    'common.follower': 'Abonné',
    'common.following': 'Suivi',
    'common.friend': 'Ami',
    'common.family': 'Famille',
    'common.colleague': 'Collègue',
    'common.partner': 'Partenaire',
    'common.client': 'Client',
    'common.customer': 'Client',
    'common.vendor': 'Fournisseur',
    'common.supplier': 'Fournisseur',
    'common.provider': 'Fournisseur',
    'common.service': 'Service',
    'common.product': 'Produit',
    'common.item': 'Article',
    'common.category': 'Catégorie',
    'common.group': 'Groupe',
    'common.team': 'Équipe',
    'common.organization': 'Organisation',
    'common.company': 'Entreprise',
    'common.department': 'Département',
    'common.division': 'Division',
    'common.branch': 'Succursale',
    'common.office': 'Bureau',
    'common.location': 'Emplacement',
    'common.address': 'Adresse',
    'common.city': 'Ville',
    'common.state': 'État',
    'common.country': 'Pays',
    'common.region': 'Région',
    'common.zone': 'Zone',
    'common.area': 'Zone',
    'common.district': 'District',
    'common.neighborhood': 'Quartier',
    'common.street': 'Rue',
    'common.building': 'Bâtiment',
    'common.floor': 'Étage',
    'common.room': 'Chambre',
    'common.unit': 'Unité',
    'common.apartment': 'Appartement',
    'common.house': 'Maison',
    'common.home': 'Domicile',
    'common.work': 'Travail',
    'common.school': 'École',
    'common.university': 'Université',
    'common.college': 'Collège',
    'common.hospital': 'Hôpital',
    'common.clinic': 'Clinique',
    'common.store': 'Magasin',
    'common.shop': 'Boutique',
    'common.market': 'Marché',
    'common.mall': 'Centre commercial',
    'common.restaurant': 'Restaurant',
    'common.cafe': 'Café',
    'common.bar': 'Bar',
    'common.hotel': 'Hôtel',
    'common.airport': 'Aéroport',
    'common.station': 'Gare',
    'common.stop': 'Arrêt',
    'common.park': 'Parc',
    'common.beach': 'Plage',
    'common.mountain': 'Montagne',
    'common.lake': 'Lac',
    'common.river': 'Rivière',
    'common.forest': 'Forêt',
    'common.desert': 'Désert',
    'common.island': 'Île',
    'common.bridge': 'Pont',
    'common.road': 'Route',
    'common.path': 'Chemin',
    'common.trail': 'Sentier',
    'common.highway': 'Autoroute',
    'common.tunnel': 'Tunnel',
    'common.entrance': 'Entrée',
    'common.exit': 'Sortie',
    'common.door': 'Porte',
    'common.window': 'Fenêtre',
    'common.wall': 'Mur',
    'common.ceiling': 'Plafond',
    'common.ground': 'Sol',
    'common.basement': 'Sous-sol',
    'common.attic': 'Grenier',
    'common.garage': 'Garage',
    'common.garden': 'Jardin',
    'common.yard': 'Cour',
    'common.balcony': 'Balcon',
    'common.terrace': 'Terrasse',
    'common.patio': 'Patio',
    'common.deck': 'Terrasse',
    'common.porch': 'Porche',
    'common.stairs': 'Escaliers',
    'common.elevator': 'Ascenseur',
    'common.escalator': 'Escalator',
    'common.hallway': 'Couloir',
    'common.corridor': 'Couloir',
    'common.lobby': 'Hall',
    'common.reception': 'Réception',
    'common.counter': 'Comptoir',
    'common.desk': 'Bureau',
    'common.table': 'Table',
    'common.chair': 'Chaise',
    'common.sofa': 'Canapé',
    'common.bed': 'Lit',
    'common.pillow': 'Oreiller',
    'common.blanket': 'Couverture',
    'common.sheet': 'Drap',
    'common.towel': 'Serviette',
    'common.mirror': 'Miroir',
    'common.picture': 'Image',
    'common.photo': 'Photo',
    'common.painting': 'Peinture',
    'common.art': 'Art',
    'common.decoration': 'Décoration',
    'common.furniture': 'Mobilier',
    'common.appliance': 'Appareil',
    'common.device': 'Appareil',
    'common.tool': 'Outil',
    'common.equipment': 'Équipement',
    'common.machine': 'Machine',
    'common.computer': 'Ordinateur',
    'common.laptop': 'Ordinateur portable',
    'common.tablet': 'Tablette',
    'common.phone': 'Téléphone',
    'common.smartphone': 'Smartphone',
    'common.camera': 'Appareil photo',
    'common.video': 'Vidéo',
    'common.audio': 'Audio',
    'common.music': 'Musique',
    'common.song': 'Chanson',
    'common.album': 'Album',
    'common.artist': 'Artiste',
    'common.band': 'Groupe',
    'common.concert': 'Concert',
    'common.show': 'Spectacle',
    'common.performance': 'Représentation',
    'common.event': 'Événement',
    'common.party': 'Fête',
    'common.celebration': 'Célébration',
    'common.festival': 'Festival',
    'common.holiday': 'Vacances',
    'common.vacation': 'Vacances',
    'common.trip': 'Voyage',
    'common.journey': 'Voyage',
    'common.adventure': 'Aventure',
    'common.experience': 'Expérience',
    'common.memory': 'Souvenir',
    'common.story': 'Histoire',
    'common.tale': 'Conte',
    'common.legend': 'Légende',
    'common.myth': 'Mythe',
    'common.fact': 'Fait',
    'common.truth': 'Vérité',
    'common.lie': 'Mensonge',
    'common.secret': 'Secret',
    'common.mystery': 'Mystère',
    'common.surprise': 'Surprise',
    'common.gift': 'Cadeau',
    'common.present': 'Cadeau',
    'common.reward': 'Récompense',
    'common.prize': 'Prix',
    'common.award': 'Prix',
    'common.medal': 'Médaille',
    'common.trophy': 'Trophée',
    'common.certificate': 'Certificat',
    'common.diploma': 'Diplôme',
    'common.degree': 'Diplôme',
    'common.qualification': 'Qualification',
    'common.skill': 'Compétence',
    'common.talent': 'Talent',
    'common.ability': 'Capacité',
    'common.knowledge': 'Connaissance',
    'common.wisdom': 'Sagesse',
    'common.intelligence': 'Intelligence',
    'common.genius': 'Génie',
    'common.expert': 'Expert',
    'common.professional': 'Professionnel',
    'common.specialist': 'Spécialiste',
    'common.master': 'Maître',
    'common.apprentice': 'Apprenti',
    'common.beginner': 'Débutant',
    'common.novice': 'Novice',
    'common.rookie': 'Débutant',
    'common.veteran': 'Vétéran',
    'common.senior': 'Senior',
    'common.junior': 'Junior',
    'common.leader': 'Leader',
    'common.manager': 'Gestionnaire',
    'common.supervisor': 'Superviseur',
    'common.director': 'Directeur',
    'common.president': 'Président',
    'common.ceo': 'PDG',
    'common.founder': 'Fondateur',
    'common.owner': 'Propriétaire',
    'common.employee': 'Employé',
    'common.worker': 'Travailleur',
    'common.staff': 'Personnel',
    'common.crew': 'Équipage',
    'common.volunteer': 'Bénévole',
    'common.intern': 'Stagiaire',
    'common.consultant': 'Consultant',
    'common.advisor': 'Conseiller',
    'common.coach': 'Entraîneur',
    'common.mentor': 'Mentor',
    'common.guide': 'Guide',
    'common.instructor': 'Instructeur',
    'common.trainer': 'Formateur',
    'common.tutor': 'Tuteur',
    'common.professor': 'Professeur',
    'common.doctor': 'Docteur',
    'common.nurse': 'Infirmière',
    'common.therapist': 'Thérapeute',
    'common.dentist': 'Dentiste',
    'common.surgeon': 'Chirurgien',
    'common.lawyer': 'Avocat',
    'common.judge': 'Juge',
    'common.police': 'Police',
    'common.officer': 'Officier',
    'common.soldier': 'Soldat',
    'common.firefighter': 'Pompier',
    'common.pilot': 'Pilote',
    'common.driver': 'Conducteur',
    'common.mechanic': 'Mécanicien',
    'common.engineer': 'Ingénieur',
    'common.architect': 'Architecte',
    'common.designer': 'Designer',
    'common.programmer': 'Programmeur',
    'common.developer': 'Développeur',
    'common.analyst': 'Analyste',
    'common.scientist': 'Scientifique',
    'common.researcher': 'Chercheur',
    'common.journalist': 'Journaliste',
    'common.reporter': 'Reporter',
    'common.writer': 'Écrivain',
    'common.author': 'Auteur',
    'common.editor': 'Éditeur',
    'common.publisher': 'Éditeur',
    'common.translator': 'Traducteur',
    'common.interpreter': 'Interprète',
    'common.actor': 'Acteur',
    'common.actress': 'Actrice',
    'common.director': 'Réalisateur',
    'common.producer': 'Producteur',
    'common.musician': 'Musicien',
    'common.singer': 'Chanteur',
    'common.dancer': 'Danseur',
    'common.athlete': 'Athlète',
    'common.player': 'Joueur',
    'common.coach': 'Entraîneur',
    'common.referee': 'Arbitre',
    'common.fan': 'Fan',
    'common.supporter': 'Supporter',
    'common.spectator': 'Spectateur',
    'common.audience': 'Public',
    'common.crowd': 'Foule',
    'common.public': 'Public',
    'common.society': 'Société',
    'common.community': 'Communauté',
    'common.neighborhood': 'Quartier',
    'common.village': 'Village',
    'common.town': 'Ville',
    'common.capital': 'Capitale',
    'common.metropolis': 'Métropole',
    'common.population': 'Population',
    'common.citizen': 'Citoyen',
    'common.resident': 'Résident',
    'common.local': 'Local',
    'common.native': 'Natif',
    'common.foreigner': 'Étranger',
    'common.tourist': 'Touriste',
    'common.visitor': 'Visiteur',
    'common.traveler': 'Voyageur',
    'common.passenger': 'Passager',
    'common.pedestrian': 'Piéton',
    'common.cyclist': 'Cycliste',
    'common.motorist': 'Automobiliste',
    'common.commuter': 'Navetteur',
    'common.transportation': 'Transport',
    'common.vehicle': 'Véhicule',
    'common.car': 'Voiture',
    'common.truck': 'Camion',
    'common.bus': 'Bus',
    'common.train': 'Train',
    'common.plane': 'Avion',
    'common.ship': 'Navire',
    'common.boat': 'Bateau',
    'common.bicycle': 'Vélo',
    'common.motorcycle': 'Moto',
    'common.scooter': 'Scooter',
    'common.taxi': 'Taxi',
    'common.uber': 'Uber',
    'common.metro': 'Métro',
    'common.subway': 'Métro',
    'common.tram': 'Tramway',
    'common.ferry': 'Ferry',
    'common.helicopter': 'Hélicoptère',
    'common.rocket': 'Fusée',
    'common.satellite': 'Satellite',
    'common.space': 'Espace',
    'common.planet': 'Planète',
    'common.earth': 'Terre',
    'common.moon': 'Lune',
    'common.sun': 'Soleil',
    'common.star': 'Étoile',
    'common.galaxy': 'Galaxie',
    'common.universe': 'Univers',
    'common.cosmos': 'Cosmos',
    'common.infinity': 'Infini',
    'common.eternity': 'Éternité',
    'common.forever': 'Pour toujours',
    'common.never': 'Jamais',
    'common.always': 'Toujours',
    'common.everywhere': 'Partout',
    'common.nowhere': 'Nulle part',
    'common.somewhere': 'Quelque part',
    'common.anywhere': 'N\'importe où',
    'common.everyone': 'Tout le monde',
    'common.nobody': 'Personne',
    'common.somebody': 'Quelqu\'un',
    'common.anybody': 'N\'importe qui',
    'common.everything': 'Tout',
    'common.nothing': 'Rien',
    'common.something': 'Quelque chose',
    'common.anything': 'N\'importe quoi',

    'button.cancel': 'Annuler',
    'button.save': 'Enregistrer',
    'button.select': 'Sélectionner',
    'button.continue': 'Continuer',
    'button.back': 'Retour',
  },
  
  // German translations
  de: {
    'profile.title': 'Confluency',
    'profile.guest': 'Gast',
    'profile.editProfile': 'Profil bearbeiten',
    'profile.settings': 'Einstellungen',
    'profile.appLanguage': 'App-Sprache',
    'profile.subscription': 'Abonnement',
    'profile.currentPlan': 'Aktueller Plan',
    'profile.support': 'Support',
    'profile.helpCenter': 'Hilfezentrum',
    'profile.contactUs': 'Kontaktieren Sie uns',
    'profile.legal': 'Rechtliches',
    'profile.privacyPolicy': 'Datenschutzrichtlinie',
    'profile.termsOfService': 'Nutzungsbedingungen',
    'profile.version': 'Version',
    'profile.logoutConfirmTitle': 'Abmeldung bestätigen',
    'profile.logoutConfirmMessage': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    'profile.logoutError': 'Bei der Abmeldung ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.',
    
    // Legacy keys
    'profile.section.subscription': 'Abonnement',
    'profile.manage.subscription': 'Abonnement verwalten',
    'profile.section.preferences': 'Einstellungen',
    'profile.app.language': 'App-Sprache',
    'profile.learning.languages': 'Lernsprachen',
    'profile.change': 'Ändern',
    'profile.section.support': 'Support',
    'profile.contact.support': 'Support kontaktieren',
    'profile.section.account': 'Konto',
    'profile.logout': 'Abmelden',
    'profile.logout.confirm.title': 'Abmeldung bestätigen',
    'profile.logout.confirm.message': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    'profile.logout.confirm.cancel': 'Abbrechen',
    'profile.logout.confirm.logout': 'Abmelden',

    'subscription.title': 'Confluency-Tokens',
    'subscription.current': 'Aktuelles Abonnement',
    'subscription.plan': 'Plan',
    'subscription.usage': 'Confluency-Tokens Nutzung',
    'subscription.reset': 'Zurückgesetzt am',
    'subscription.available.plans': 'Verfügbare Pläne',
    'subscription.restore': 'Käufe wiederherstellen',
    'subscription.expo.notice': 'Läuft im Entwicklungsmodus. Käufe werden simuliert und nicht berechnet.',
    'subscription.legal.text': 'Abonnements werden automatisch verlängert, es sei denn, die automatische Verlängerung wird mindestens 24 Stunden vor Ende des aktuellen Zeitraums deaktiviert.',
    'subscription.manage.text': 'Sie können Ihre Abonnements in den Einstellungen Ihres App Store/Google Play-Kontos nach dem Kauf verwalten.',
    
    'language.i.speak': 'Ich spreche:',
    'language.want.to.learn': 'Ich möchte lernen:',
    'language.difficulty': 'Schwierigkeitsgrad:',
    'language.conversation.mode': 'Konversationsmodus:',
    'language.learning.objective': 'Lernziel (optional):',
    'language.start.button': 'Mit dem Lernen beginnen',
    'language.app.title': 'App-Sprache',

    // Conversation Mode Translations
    'conversation.categories.conversations': 'Unterhaltungen',
    'conversation.categories.languageLessons': 'Sprachlektionen',
    'conversation.freeConversation.label': 'Freie Unterhaltung',
    'conversation.freeConversation.description': 'Führen Sie natürliche, unstrukturierte Gespräche über jedes Thema, das Sie interessiert.',
    'conversation.freeConversation.placeholder': '• Game of Thrones\n• Golf-Tipps\n• Urlaubsziele',
    'conversation.topicLesson.label': 'Spezial-Themen-Lektion',
    'conversation.topicLesson.description': 'Entdecken Sie faszinierende Themen in Ihrer Zielsprache - Geschichte, Kultur, Sport, Geopolitik...',
    'conversation.topicLesson.placeholder': '• Geschichte Roms\n• Hundetraining-Tipps\n• Moderne Kunstbewegungen',
    'conversation.interview.label': 'Interview',
    'conversation.interview.description': 'Drücken Sie sich natürlich aus, während Sie Fragen zu Ihren Interessen, Erfahrungen und Meinungen beantworten.',
    'conversation.interview.placeholder': '• Ihre Hobbys\n• Reiseerfahrungen\n• Lebensziele',
    'conversation.situationSimulation.label': 'Situationssimulation',
    'conversation.situationSimulation.description': 'Üben Sie reale Gespräche in alltäglichen Szenarien wie Restaurants, Reisen und Einkaufen.',
    'conversation.situationSimulation.placeholder': '• Im Restaurant\n• Bewerbungsgespräch\n• Flughafen-Check-in\n• Kleidung einkaufen',
    'conversation.verbChallenge.label': 'Verb-Herausforderung',
    'conversation.verbChallenge.description': 'Üben Sie den Satzbau mit wichtigen Verben in verschiedenen Zeiten und Modi.',
    'conversation.verbChallenge.placeholder': '• Spezifische Verbzeiten zum Üben\n• Schwierigkeitsgrad-Präferenzen\n• Verbtypen',
    'conversation.verbChallenge.comingSoon': 'Demnächst verfügbar',
    'conversation.topicTheme.label': 'Thema/Betreff',
    'conversation.generateRandomTopic': 'Zufälliges Thema generieren',
    'conversation.selectMode': 'Gesprächsmodus auswählen',
    'conversation.topicInfo': 'Confluency kann mit Ihnen über jedes erdenkliche Thema sprechen: von Dating-Tipps bis zum Tanzen, vom alten Ägypten bis zu Taylor Swift!',
    'loading.generating': 'Wird generiert...',

    // Email Verification
    'email.verification.title': 'E-Mail-Verifizierung erforderlich',
    'email.verification.message': 'Ihre E-Mail-Adresse muss verifiziert werden, bevor Sie fortfahren können. Bitte überprüfen Sie Ihren Posteingang (einschließlich Spam-Ordner) auf eine Verifizierungs-E-Mail oder verwenden Sie die Schaltfläche "E-Mail erneut senden" unten.',
    'email.verification.ok': 'OK',
    'email.verification.resendEmail': 'E-Mail erneut senden',
    'email.verification.checkingVerification': 'Überprüfung...',
    'email.verification.emailSent': 'E-Mail gesendet',
    'email.verification.emailSentMessage': 'Eine neue Verifizierungs-E-Mail wurde gesendet. Bitte überprüfen Sie Ihren Posteingang.',
    'email.verification.errorSending': 'Fehler beim Senden',
    'email.verification.errorSendingMessage': 'Die Verifizierungs-E-Mail konnte nicht gesendet werden. Bitte versuchen Sie es erneut.',
    'email.verification.verificationComplete': 'Verifizierung abgeschlossen',
    'email.verification.verificationCompleteMessage': 'Ihre E-Mail wurde erfolgreich verifiziert.',
    'email.verification.networkError': 'Verbindungsfehler',
    'email.verification.networkErrorMessage': 'Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.',
    'email.verification.notVerified': 'Ihre E-Mail ist noch nicht verifiziert. Bitte überprüfen Sie Ihren Posteingang und klicken Sie auf den Verifizierungslink.',
    'email.verification.checkEmail': 'Bitte überprüfen Sie Ihre E-Mail und klicken Sie auf den Verifizierungslink, um Ihr Konto zu aktivieren.',
    'email.verification.checkEmailTitle': 'Überprüfen Sie Ihre E-Mail',
    'email.verification.checkEmailMessage': 'Bitte überprüfen Sie Ihren Posteingang und klicken Sie auf den Verifizierungslink, um Ihr Konto zu aktivieren. Nach der Verifizierung werden Sie automatisch angemeldet.',
    'email.verification.cannotOpenEmail': 'E-Mail kann nicht geöffnet werden',
    'email.verification.cannotOpenEmailMessage': 'Ihre E-Mail-App konnte nicht geöffnet werden. Bitte überprüfen Sie Ihren Posteingang manuell.',

    // Common
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.loading': 'Lädt...',
    'common.tryAgain': 'Erneut versuchen',
    'common.cancel': 'Abbrechen',
    'common.ok': 'OK',
    'common.yes': 'Ja',
    'common.no': 'Nein',
    'common.close': 'Schließen',
    'common.done': 'Fertig',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.skip': 'Überspringen',
    'common.required': 'Erforderlich',
    'common.optional': 'Optional',
    'common.email': 'E-Mail',
    'common.password': 'Passwort',
    'common.confirmPassword': 'Passwort bestätigen',
    'common.firstName': 'Vorname',
    'common.lastName': 'Nachname',
    'common.name': 'Name',
    'common.username': 'Benutzername',
    'common.language': 'Sprache',
    'common.difficulty': 'Schwierigkeit',
    'common.beginner': 'Anfänger',
    'common.intermediate': 'Fortgeschritten',
    'common.advanced': 'Experte',
    'common.save': 'Speichern',
    'common.edit': 'Bearbeiten',
    'common.delete': 'Löschen',
    'common.remove': 'Entfernen',
    'common.add': 'Hinzufügen',
    'common.create': 'Erstellen',
    'common.update': 'Aktualisieren',
    'common.search': 'Suchen',
    'common.filter': 'Filter',
    'common.sort': 'Sortieren',
    'common.refresh': 'Aktualisieren',
    'common.retry': 'Wiederholen',
    'common.continue': 'Fortfahren',
    'common.start': 'Starten',
    'common.stop': 'Stoppen',
    'common.pause': 'Pause',
    'common.play': 'Abspielen',
    'common.record': 'Aufnehmen',
    'common.send': 'Senden',
    'common.receive': 'Empfangen',
    'common.upload': 'Hochladen',
    'common.download': 'Herunterladen',
    'common.share': 'Teilen',
    'common.copy': 'Kopieren',
    'common.paste': 'Einfügen',
    'common.cut': 'Ausschneiden',
    'common.undo': 'Rückgängig',
    'common.redo': 'Wiederholen',
    'common.settings': 'Einstellungen',
    'common.preferences': 'Einstellungen',
    'common.help': 'Hilfe',
    'common.about': 'Über',
    'common.contact': 'Kontakt',
    'common.support': 'Support',
    'common.feedback': 'Feedback',
    'common.report': 'Melden',
    'common.terms': 'Bedingungen',
    'common.privacy': 'Datenschutz',
    'common.legal': 'Rechtliches',
    'common.version': 'Version',
    'common.update': 'Aktualisierung',
    'common.latest': 'Neueste',
    'common.new': 'Neu',
    'common.old': 'Alt',
    'common.recent': 'Kürzlich',
    'common.popular': 'Beliebt',
    'common.featured': 'Empfohlen',
    'common.recommended': 'Empfohlen',
    'common.favorite': 'Favorit',
    'common.bookmark': 'Lesezeichen',
    'common.like': 'Gefällt mir',
    'common.dislike': 'Gefällt mir nicht',
    'common.rating': 'Bewertung',
    'common.review': 'Bewertung',
    'common.comment': 'Kommentar',
    'common.reply': 'Antworten',
    'common.message': 'Nachricht',
    'common.notification': 'Benachrichtigung',
    'common.alert': 'Warnung',
    'common.warning': 'Warnung',
    'common.info': 'Information',
    'common.tip': 'Tipp',
    'common.note': 'Notiz',
    'common.reminder': 'Erinnerung',
    'common.date': 'Datum',
    'common.time': 'Zeit',
    'common.today': 'Heute',
    'common.yesterday': 'Gestern',
    'common.tomorrow': 'Morgen',
    'common.week': 'Woche',
    'common.month': 'Monat',
    'common.year': 'Jahr',
    'common.daily': 'Täglich',
    'common.weekly': 'Wöchentlich',
    'common.monthly': 'Monatlich',
    'common.yearly': 'Jährlich',
    'common.never': 'Nie',
    'common.always': 'Immer',
    'common.sometimes': 'Manchmal',
    'common.often': 'Oft',
    'common.rarely': 'Selten',
    'common.all': 'Alle',
    'common.none': 'Keine',
    'common.some': 'Einige',
    'common.many': 'Viele',
    'common.few': 'Wenige',
    'common.more': 'Mehr',
    'common.less': 'Weniger',
    'common.most': 'Die meisten',
    'common.least': 'Am wenigsten',
    'common.best': 'Beste',
    'common.worst': 'Schlechteste',
    'common.better': 'Besser',
    'common.worse': 'Schlechter',
    'common.same': 'Gleich',
    'common.different': 'Unterschiedlich',
    'common.similar': 'Ähnlich',
    'common.equal': 'Gleich',
    'common.unique': 'Einzigartig',
    'common.special': 'Besonders',
    'common.normal': 'Normal',
    'common.standard': 'Standard',
    'common.custom': 'Benutzerdefiniert',
    'common.default': 'Standard',
    'common.auto': 'Automatisch',
    'common.manual': 'Manuell',
    'common.enabled': 'Aktiviert',
    'common.disabled': 'Deaktiviert',
    'common.on': 'Ein',
    'common.off': 'Aus',
    'common.true': 'Wahr',
    'common.false': 'Falsch',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.connected': 'Verbunden',
    'common.disconnected': 'Getrennt',
    'common.available': 'Verfügbar',
    'common.unavailable': 'Nicht verfügbar',
    'common.busy': 'Beschäftigt',
    'common.free': 'Frei',
    'common.premium': 'Premium',
    'common.pro': 'Pro',
    'common.basic': 'Basis',
    'common.trial': 'Testversion',
    'common.demo': 'Demo',
    'common.beta': 'Beta',
    'common.alpha': 'Alpha',
    'common.stable': 'Stabil',
    'common.experimental': 'Experimentell',
    'common.public': 'Öffentlich',
    'common.private': 'Privat',
    'common.personal': 'Persönlich',
    'common.business': 'Geschäftlich',
    'common.professional': 'Professionell',
    'common.student': 'Student',
    'common.teacher': 'Lehrer',
    'common.admin': 'Administrator',
    'common.user': 'Benutzer',
    'common.guest': 'Gast',
    'common.member': 'Mitglied',
    'common.subscriber': 'Abonnent',
    'common.follower': 'Follower',
    'common.following': 'Folgend',
    'common.friend': 'Freund',
    'common.family': 'Familie',
    'common.colleague': 'Kollege',
    'common.partner': 'Partner',
    'common.client': 'Kunde',
    'common.customer': 'Kunde',
    'common.vendor': 'Anbieter',
    'common.supplier': 'Lieferant',
    'common.provider': 'Anbieter',
    'common.service': 'Service',
    'common.product': 'Produkt',
    'common.item': 'Artikel',
    'common.category': 'Kategorie',
    'common.group': 'Gruppe',
    'common.team': 'Team',
    'common.organization': 'Organisation',
    'common.company': 'Unternehmen',
    'common.department': 'Abteilung',
    'common.division': 'Bereich',
    'common.branch': 'Filiale',
    'common.office': 'Büro',
    'common.location': 'Standort',
    'common.address': 'Adresse',
    'common.city': 'Stadt',
    'common.state': 'Staat',
    'common.country': 'Land',
    'common.region': 'Region',
    'common.zone': 'Zone',
    'common.area': 'Bereich',
    'common.district': 'Bezirk',
    'common.neighborhood': 'Nachbarschaft',
    'common.street': 'Straße',
    'common.building': 'Gebäude',
    'common.floor': 'Etage',
    'common.room': 'Raum',
    'common.unit': 'Einheit',
    'common.apartment': 'Wohnung',
    'common.house': 'Haus',
    'common.home': 'Zuhause',
    'common.work': 'Arbeit',
    'common.school': 'Schule',
    'common.university': 'Universität',
    'common.college': 'Hochschule',
    'common.hospital': 'Krankenhaus',
    'common.clinic': 'Klinik',
    'common.store': 'Geschäft',
    'common.shop': 'Laden',
    'common.market': 'Markt',
    'common.mall': 'Einkaufszentrum',
    'common.restaurant': 'Restaurant',
    'common.cafe': 'Café',
    'common.bar': 'Bar',
    'common.hotel': 'Hotel',
    'common.airport': 'Flughafen',
    'common.station': 'Bahnhof',
    'common.stop': 'Haltestelle',
    'common.park': 'Park',
    'common.beach': 'Strand',
    'common.mountain': 'Berg',
    'common.lake': 'See',
    'common.river': 'Fluss',
    'common.forest': 'Wald',
    'common.desert': 'Wüste',
    'common.island': 'Insel',
    'common.bridge': 'Brücke',
    'common.road': 'Straße',
    'common.path': 'Pfad',
    'common.trail': 'Weg',
    'common.highway': 'Autobahn',
    'common.tunnel': 'Tunnel',
    'common.entrance': 'Eingang',
    'common.exit': 'Ausgang',
    'common.door': 'Tür',
    'common.window': 'Fenster',
    'common.wall': 'Wand',
    'common.ceiling': 'Decke',
    'common.ground': 'Boden',
    'common.basement': 'Keller',
    'common.attic': 'Dachboden',
    'common.garage': 'Garage',
    'common.garden': 'Garten',
    'common.yard': 'Hof',
    'common.balcony': 'Balkon',
    'common.terrace': 'Terrasse',
    'common.patio': 'Terrasse',
    'common.deck': 'Terrasse',
    'common.porch': 'Veranda',
    'common.stairs': 'Treppe',
    'common.elevator': 'Aufzug',
    'common.escalator': 'Rolltreppe',
    'common.hallway': 'Flur',
    'common.corridor': 'Korridor',
    'common.lobby': 'Lobby',
    'common.reception': 'Rezeption',
    'common.counter': 'Theke',
    'common.desk': 'Schreibtisch',
    'common.table': 'Tisch',
    'common.chair': 'Stuhl',
    'common.sofa': 'Sofa',
    'common.bed': 'Bett',
    'common.pillow': 'Kissen',
    'common.blanket': 'Decke',
    'common.sheet': 'Laken',
    'common.towel': 'Handtuch',
    'common.mirror': 'Spiegel',
    'common.picture': 'Bild',
    'common.photo': 'Foto',
    'common.painting': 'Gemälde',
    'common.art': 'Kunst',
    'common.decoration': 'Dekoration',
    'common.furniture': 'Möbel',
    'common.appliance': 'Gerät',
    'common.device': 'Gerät',
    'common.tool': 'Werkzeug',
    'common.equipment': 'Ausrüstung',
    'common.machine': 'Maschine',
    'common.computer': 'Computer',
    'common.laptop': 'Laptop',
    'common.tablet': 'Tablet',
    'common.phone': 'Telefon',
    'common.smartphone': 'Smartphone',
    'common.camera': 'Kamera',
    'common.video': 'Video',
    'common.audio': 'Audio',
    'common.music': 'Musik',
    'common.song': 'Lied',
    'common.album': 'Album',
    'common.artist': 'Künstler',
    'common.band': 'Band',
    'common.concert': 'Konzert',
    'common.show': 'Show',
    'common.performance': 'Aufführung',
    'common.event': 'Veranstaltung',
    'common.party': 'Party',
    'common.celebration': 'Feier',
    'common.festival': 'Festival',
    'common.holiday': 'Feiertag',
    'common.vacation': 'Urlaub',
    'common.trip': 'Reise',
    'common.journey': 'Reise',
    'common.adventure': 'Abenteuer',
    'common.experience': 'Erfahrung',
    'common.memory': 'Erinnerung',
    'common.story': 'Geschichte',
    'common.tale': 'Erzählung',
    'common.legend': 'Legende',
    'common.myth': 'Mythos',
    'common.fact': 'Tatsache',
    'common.truth': 'Wahrheit',
    'common.lie': 'Lüge',
    'common.secret': 'Geheimnis',
    'common.mystery': 'Geheimnis',
    'common.surprise': 'Überraschung',
    'common.gift': 'Geschenk',
    'common.present': 'Geschenk',
    'common.reward': 'Belohnung',
    'common.prize': 'Preis',
    'common.award': 'Auszeichnung',
    'common.medal': 'Medaille',
    'common.trophy': 'Trophäe',
    'common.certificate': 'Zertifikat',
    'common.diploma': 'Diplom',
    'common.degree': 'Abschluss',
    'common.qualification': 'Qualifikation',
    'common.skill': 'Fähigkeit',
    'common.talent': 'Talent',
    'common.ability': 'Fähigkeit',
    'common.knowledge': 'Wissen',
    'common.wisdom': 'Weisheit',
    'common.intelligence': 'Intelligenz',
    'common.genius': 'Genie',
    'common.expert': 'Experte',
    'common.professional': 'Profi',
    'common.specialist': 'Spezialist',
    'common.master': 'Meister',
    'common.apprentice': 'Lehrling',
    'common.beginner': 'Anfänger',
    'common.novice': 'Neuling',
    'common.rookie': 'Anfänger',
    'common.veteran': 'Veteran',
    'common.senior': 'Senior',
    'common.junior': 'Junior',
    'common.leader': 'Anführer',
    'common.manager': 'Manager',
    'common.supervisor': 'Vorgesetzter',
    'common.director': 'Direktor',
    'common.president': 'Präsident',
    'common.ceo': 'CEO',
    'common.founder': 'Gründer',
    'common.owner': 'Eigentümer',
    'common.employee': 'Angestellter',
    'common.worker': 'Arbeiter',
    'common.staff': 'Personal',
    'common.crew': 'Crew',
    'common.volunteer': 'Freiwilliger',
    'common.intern': 'Praktikant',
    'common.consultant': 'Berater',
    'common.advisor': 'Berater',
    'common.coach': 'Trainer',
    'common.mentor': 'Mentor',
    'common.guide': 'Führer',
    'common.instructor': 'Instruktor',
    'common.trainer': 'Trainer',
    'common.tutor': 'Tutor',
    'common.professor': 'Professor',
    'common.doctor': 'Arzt',
    'common.nurse': 'Krankenschwester',
    'common.therapist': 'Therapeut',
    'common.dentist': 'Zahnarzt',
    'common.surgeon': 'Chirurg',
    'common.lawyer': 'Anwalt',
    'common.judge': 'Richter',
    'common.police': 'Polizei',
    'common.officer': 'Offizier',
    'common.soldier': 'Soldat',
    'common.firefighter': 'Feuerwehrmann',
    'common.pilot': 'Pilot',
    'common.driver': 'Fahrer',
    'common.mechanic': 'Mechaniker',
    'common.engineer': 'Ingenieur',
    'common.architect': 'Architekt',
    'common.designer': 'Designer',
    'common.programmer': 'Programmierer',
    'common.developer': 'Entwickler',
    'common.analyst': 'Analyst',
    'common.scientist': 'Wissenschaftler',
    'common.researcher': 'Forscher',
    'common.journalist': 'Journalist',
    'common.reporter': 'Reporter',
    'common.writer': 'Schriftsteller',
    'common.author': 'Autor',
    'common.editor': 'Redakteur',
    'common.publisher': 'Verleger',
    'common.translator': 'Übersetzer',
    'common.interpreter': 'Dolmetscher',
    'common.actor': 'Schauspieler',
    'common.actress': 'Schauspielerin',
    'common.director': 'Regisseur',
    'common.producer': 'Produzent',
    'common.musician': 'Musiker',
    'common.singer': 'Sänger',
    'common.dancer': 'Tänzer',
    'common.athlete': 'Athlet',
    'common.player': 'Spieler',
    'common.coach': 'Trainer',
    'common.referee': 'Schiedsrichter',
    'common.fan': 'Fan',
    'common.supporter': 'Anhänger',
    'common.spectator': 'Zuschauer',
    'common.audience': 'Publikum',
    'common.crowd': 'Menschenmenge',
    'common.public': 'Öffentlichkeit',
    'common.society': 'Gesellschaft',
    'common.community': 'Gemeinschaft',
    'common.neighborhood': 'Nachbarschaft',
    'common.village': 'Dorf',
    'common.town': 'Stadt',
    'common.capital': 'Hauptstadt',
    'common.metropolis': 'Metropole',
    'common.population': 'Bevölkerung',
    'common.citizen': 'Bürger',
    'common.resident': 'Bewohner',
    'common.local': 'Einheimischer',
    'common.native': 'Eingeborener',
    'common.foreigner': 'Ausländer',
    'common.tourist': 'Tourist',
    'common.visitor': 'Besucher',
    'common.traveler': 'Reisender',
    'common.passenger': 'Passagier',
    'common.pedestrian': 'Fußgänger',
    'common.cyclist': 'Radfahrer',
    'common.motorist': 'Autofahrer',
    'common.commuter': 'Pendler',
    'common.transportation': 'Transport',
    'common.vehicle': 'Fahrzeug',
    'common.car': 'Auto',
    'common.truck': 'LKW',
    'common.bus': 'Bus',
    'common.train': 'Zug',
    'common.plane': 'Flugzeug',
    'common.ship': 'Schiff',
    'common.boat': 'Boot',
    'common.bicycle': 'Fahrrad',
    'common.motorcycle': 'Motorrad',
    'common.scooter': 'Roller',
    'common.taxi': 'Taxi',
    'common.uber': 'Uber',
    'common.metro': 'U-Bahn',
    'common.subway': 'U-Bahn',
    'common.tram': 'Straßenbahn',
    'common.ferry': 'Fähre',
    'common.helicopter': 'Hubschrauber',
    'common.rocket': 'Rakete',
    'common.satellite': 'Satellit',
    'common.space': 'Weltraum',
    'common.planet': 'Planet',
    'common.earth': 'Erde',
    'common.moon': 'Mond',
    'common.sun': 'Sonne',
    'common.star': 'Stern',
    'common.galaxy': 'Galaxie',
    'common.universe': 'Universum',
    'common.cosmos': 'Kosmos',
    'common.infinity': 'Unendlichkeit',
    'common.eternity': 'Ewigkeit',
    'common.forever': 'Für immer',
    'common.never': 'Niemals',
    'common.always': 'Immer',
    'common.everywhere': 'Überall',
    'common.nowhere': 'Nirgendwo',
    'common.somewhere': 'Irgendwo',
    'common.anywhere': 'Überall',
    'common.everyone': 'Jeder',
    'common.nobody': 'Niemand',
    'common.somebody': 'Jemand',
    'common.anybody': 'Irgendjemand',
    'common.everything': 'Alles',
    'common.nothing': 'Nichts',
    'common.something': 'Etwas',
    'common.anything': 'Alles',

    'button.cancel': 'Abbrechen',
    'button.save': 'Speichern',
    'button.select': 'Auswählen',
    'button.continue': 'Fortfahren',
    'button.back': 'Zurück',
  },
  
  // Chinese translations
  zh: {
    'profile.title': 'Confluency',
    'profile.section.subscription': '订阅',
    'profile.manage.subscription': '管理订阅',
    'profile.section.preferences': '偏好设置',
    'profile.app.language': '应用语言',
    'profile.learning.languages': '学习语言',
    'profile.change': '更改',
    'profile.section.support': '支持',
    'profile.contact.support': '联系支持',
    'profile.section.account': '账户',
    'profile.logout': '退出登录',
    'profile.logout.confirm.title': '确认退出',
    'profile.logout.confirm.message': '您确定要退出登录吗？',
    'profile.logout.confirm.cancel': '取消',
    'profile.logout.confirm.logout': '退出登录',

    'subscription.title': 'Confluency代币',
    'subscription.current': '当前订阅',
    'subscription.plan': '方案',
    'subscription.usage': 'Confluency代币使用情况',
    'subscription.reset': '重置于',
    'subscription.available.plans': '可用方案',
    'subscription.restore': '恢复购买',
    'subscription.expo.notice': '在开发模式下运行。购买被模拟，不会收费。',
    'subscription.legal.text': '除非在当前期限结束前至少24小时关闭自动续订，否则订阅将自动续订。',
    'subscription.manage.text': '购买后，您可以在App Store/Google Play帐户设置中管理您的订阅。',
    
    'language.i.speak': '我说:',
    'language.want.to.learn': '我想学习:',
    'language.difficulty': '难度:',
    'language.conversation.mode': '对话模式:',
    'language.learning.objective': '学习目标（可选）:',
    'language.start.button': '开始学习',
    'language.app.title': '应用语言',

    // Common
    'common.error': '错误',
    
    'button.cancel': '取消',
    'button.save': '保存',
    'button.select': '选择',
    'button.continue': '继续',
    'button.back': '返回',
  },
  
  // Italian translations
  it: {
    // Profile Screen
    'profile.title': 'Confluency',
    'profile.guest': 'Ospite',
    'profile.editProfile': 'Modifica Profilo',
    'profile.settings': 'Impostazioni',
    'profile.appLanguage': 'Lingua dell\'App',
    'profile.subscription': 'Abbonamento',
    'profile.currentPlan': 'Piano Attuale',
    'profile.support': 'Supporto',
    'profile.helpCenter': 'Centro Assistenza',
    'profile.contactUs': 'Contattaci',
    'profile.legal': 'Legale',
    'profile.privacyPolicy': 'Informativa sulla Privacy',
    'profile.termsOfService': 'Termini di Servizio',
    'profile.version': 'Versione',
    'profile.logoutConfirmTitle': 'Conferma Logout',
    'profile.logoutConfirmMessage': 'Sei sicuro di voler disconnetterti?',
    'profile.logoutError': 'Si è verificato un errore durante il logout. Riprova.',
    
    // Legacy keys (keeping for backward compatibility)
    'profile.section.subscription': 'Abbonamento',
    'profile.manage.subscription': 'Gestisci Abbonamento',
    'profile.section.preferences': 'Preferenze',
    'profile.app.language': 'Lingua dell\'App',
    'profile.learning.languages': 'Lingue di Apprendimento',
    'profile.change': 'Cambia',
    'profile.section.support': 'Supporto',
    'profile.contact.support': 'Contatta il Supporto',
    'profile.section.account': 'Account',
    'profile.logout': 'Disconnetti',
    'profile.logout.confirm.title': 'Conferma Logout',
    'profile.logout.confirm.message': 'Sei sicuro di voler disconnetterti?',
    'profile.logout.confirm.cancel': 'Annulla',
    'profile.logout.confirm.logout': 'Disconnetti',

    // Subscription Screen
    'subscription.title': 'Token di Confluency',
    'subscription.current': 'Abbonamento Attuale',
    'subscription.plan': 'Piano',
    'subscription.usage': 'Utilizzo Token di Confluency',
    'subscription.reset': 'Si reimposta il',
    'subscription.available.plans': 'Piani Disponibili',
    'subscription.restore': 'Ripristina Acquisti',
    'subscription.expo.notice': 'In modalità sviluppo. Gli acquisti sono simulati e non addebitati.',
    'subscription.legal.text': 'Gli abbonamenti si rinnoveranno automaticamente a meno che il rinnovo automatico non venga disattivato almeno 24 ore prima della fine del periodo corrente.',
    'subscription.manage.text': 'Puoi gestire i tuoi abbonamenti nelle impostazioni del tuo account App Store/Google Play dopo l\'acquisto.',
    
    // Language Selection
    'language.i.speak': 'Io parlo:',
    'language.want.to.learn': 'Voglio imparare:',
    'language.difficulty': 'Difficoltà:',
    'language.conversation.mode': 'Modalità di Conversazione:',
    'language.learning.objective': 'Obiettivo di Apprendimento (opzionale):',
    'language.start.button': 'Inizia ad Imparare',
    'language.app.title': 'Lingua dell\'App',

    // Conversation Mode Translations
    'conversation.categories.conversations': 'Conversazioni',
    'conversation.categories.languageLessons': 'Lezioni di Lingua',
    'conversation.freeConversation.label': 'Conversazione Libera',
    'conversation.freeConversation.description': 'Partecipa a conversazioni naturali e non strutturate su qualsiasi argomento che ti interessa.',
    'conversation.freeConversation.placeholder': '• Il Trono di Spade\n• Consigli per il Golf\n• Destinazioni per le Vacanze',
    'conversation.topicLesson.label': 'Lezione su Argomento Speciale',
    'conversation.topicLesson.description': 'Esplora argomenti affascinanti nella tua lingua di destinazione - storia, cultura, sport, geopolitica...',
    'conversation.topicLesson.placeholder': '• Storia di Roma\n• Consigli per l\'Addestramento del Cane\n• Movimenti dell\'Arte Moderna',
    'conversation.interview.label': 'Intervista',
    'conversation.interview.description': 'Esprimi te stesso naturalmente mentre rispondi a domande sui tuoi interessi, esperienze e opinioni.',
    'conversation.interview.placeholder': '• I Tuoi Hobby\n• Esperienze di Viaggio\n• Obiettivi di Vita',
    'conversation.situationSimulation.label': 'Simulazione di Situazione',
    'conversation.situationSimulation.description': 'Pratica conversazioni della vita reale in scenari comuni come ristoranti, viaggi e shopping.',
    'conversation.situationSimulation.placeholder': '• In un ristorante\n• Colloquio di lavoro\n• Check-in aeroporto\n• Comprare vestiti',
    'conversation.verbChallenge.label': 'Sfida dei Verbi',
    'conversation.verbChallenge.description': 'Pratica la costruzione di frasi con verbi essenziali in diversi tempi e modi.',
    'conversation.verbChallenge.placeholder': '• Tempi verbali specifici da praticare\n• Preferenze del livello di difficoltà\n• Tipi di verbi',
    'conversation.verbChallenge.comingSoon': 'Prossimamente',
    'conversation.topicTheme.label': 'Argomento/Tema',
    'conversation.generateRandomTopic': 'Genera Argomento Casuale',
    'conversation.selectMode': 'Seleziona Modalità di Conversazione',
    'conversation.topicInfo': 'Confluency può parlare con te di qualsiasi argomento tu possa immaginare - dai consigli per gli appuntamenti alla danza, dall\'Antico Egitto a Taylor Swift!',
    'loading.generating': 'Generando...',

    // Email Verification
    'email.verification.title': 'Verifica Email Richiesta',
    'email.verification.message': 'Il tuo indirizzo email deve essere verificato prima di poter continuare. Controlla la tua casella di posta (inclusa la cartella spam) per un\'email di verifica, o usa il pulsante "Invia di Nuovo Email" qui sotto.',
    'email.verification.ok': 'OK',
    'email.verification.resendEmail': 'Invia di Nuovo Email',
    'email.verification.checkingVerification': 'Controllo verifica...',
    'email.verification.emailSent': 'Email Inviata',
    'email.verification.emailSentMessage': 'Una nuova email di verifica è stata inviata. Controlla la tua casella di posta.',
    'email.verification.errorSending': 'Errore nell\'Invio',
    'email.verification.errorSendingMessage': 'Impossibile inviare l\'email di verifica. Riprova.',
    'email.verification.verificationComplete': 'Verifica Completata',
    'email.verification.verificationCompleteMessage': 'La tua email è stata verificata con successo.',
    'email.verification.networkError': 'Errore di Connessione',
    'email.verification.networkErrorMessage': 'Controlla la tua connessione internet e riprova.',
    'email.verification.notVerified': 'La tua email non è ancora verificata. Controlla la tua casella di posta e clicca sul link di verifica.',
    'email.verification.checkEmail': 'Controlla la tua email e clicca sul link di verifica per attivare il tuo account.',
    'email.verification.checkEmailTitle': 'Controlla la Tua Email',
    'email.verification.checkEmailMessage': 'Controlla la tua casella di posta email e clicca sul link di verifica per attivare il tuo account. Dopo la verifica, sarai automaticamente connesso.',
    'email.verification.cannotOpenEmail': 'Impossibile Aprire Email',
    'email.verification.cannotOpenEmailMessage': 'Impossibile aprire la tua app email. Controlla manualmente la tua casella di posta email.',
    'email.verification.verifyTitle': 'Verifica la Tua Email',
    'email.verification.sentTo': 'Abbiamo inviato un\'email di verifica a:',
    'email.verification.instructions': 'Controlla la tua casella di posta e clicca sul link di verifica per attivare il tuo account. Non dimenticare di controllare la tua cartella spam o posta indesiderata.',
    'email.verification.offlineWarning': 'Sei offline. Connettiti a internet per verificare la tua email.',
    'email.verification.openEmailApp': 'Apri App Email',
    'email.verification.verifiedButton': 'Ho Verificato la Mia Email',
    'email.verification.helpText': 'Hai problemi? Controlla la tua cartella spam o contatta il nostro team di supporto per assistenza.',

    // Quota Exceeded Modal
    'quota.exceeded.title': 'Limite Token Raggiunto',
    'quota.exceeded.message': 'Hai raggiunto il tuo limite mensile di token per l\'apprendimento delle lingue. Aggiorna il tuo abbonamento per continuare a imparare senza limiti.',
    'quota.exceeded.upgradeNow': 'Aggiorna Ora',
    'quota.exceeded.notNow': 'Non Ora',

    // Loading States
    'loading.general': 'Caricamento...',
    'loading.savingPreferences': 'Salvataggio preferenze...',
    'loading.connecting': 'Connessione...',
    'loading.verifying': 'Verifica...',
    'loading.sendingEmail': 'Invio email...',

    // Status Messages
    'status.offline': 'Offline',
    'status.connecting': 'Connessione...',
    'status.connected': 'Connesso',
    'status.disconnected': 'Disconnesso',

    // Error Messages
    'error.network.title': 'Errore di Connessione',
    'error.network.message': 'Impossibile connettersi al server. Controlla la tua connessione internet.',
    'error.auth.generic': 'Errore di autenticazione. Riprova.',
    'error.auth.network': 'Errore di rete durante l\'autenticazione.',
    'error.subscription.failed': 'Elaborazione abbonamento fallita.',
    'error.verification.failed': 'Verifica email fallita.',

    // Placeholders
    'placeholder.learningObjective': 'es. storia romana, cultura giapponese...',
    'placeholder.searchLanguages': 'Cerca lingue...',
    'placeholder.email': 'tua@email.com',
    'placeholder.password': 'Password',

    // Accessibility Labels
    'accessibility.closeModal': 'Chiudi modale',
    'accessibility.selectLanguage': 'Seleziona lingua',
    'accessibility.backButton': 'Pulsante indietro',
    'accessibility.menuButton': 'Pulsante menu',

    // Additional Button Labels
    'button.upgradeNow': 'Aggiorna Ora',
    'button.notNow': 'Non Ora',
    'button.resendEmail': 'Invia di Nuovo Email',
    'button.tryAgain': 'Riprova',
    'button.ok': 'OK',

    // Common
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.warning': 'Avviso',
    'common.info': 'Info',
    
    // Buttons
    'button.cancel': 'Annulla',
    'button.save': 'Salva',
    'button.select': 'Seleziona',
    'button.continue': 'Continua',
    'button.back': 'Indietro',
  },
  
  // Portuguese translations
  pt: {
    // Profile Screen
    'profile.title': 'Confluency',
    'profile.guest': 'Convidado',
    'profile.editProfile': 'Editar Perfil',
    'profile.settings': 'Configurações',
    'profile.appLanguage': 'Idioma do App',
    'profile.subscription': 'Assinatura',
    'profile.currentPlan': 'Plano Atual',
    'profile.support': 'Suporte',
    'profile.helpCenter': 'Central de Ajuda',
    'profile.contactUs': 'Entre em Contato',
    'profile.legal': 'Legal',
    'profile.privacyPolicy': 'Política de Privacidade',
    'profile.termsOfService': 'Termos de Serviço',
    'profile.version': 'Versão',
    'profile.logoutConfirmTitle': 'Confirmar Logout',
    'profile.logoutConfirmMessage': 'Tem certeza de que deseja sair?',
    'profile.logoutError': 'Ocorreu um erro durante o logout. Tente novamente.',
    
    // Legacy keys (keeping for backward compatibility)
    'profile.section.subscription': 'Assinatura',
    'profile.manage.subscription': 'Gerenciar Assinatura',
    'profile.section.preferences': 'Preferências',
    'profile.app.language': 'Idioma do App',
    'profile.learning.languages': 'Idiomas de Aprendizado',
    'profile.change': 'Alterar',
    'profile.section.support': 'Suporte',
    'profile.contact.support': 'Contatar Suporte',
    'profile.section.account': 'Conta',
    'profile.logout': 'Sair',
    'profile.logout.confirm.title': 'Confirmar Logout',
    'profile.logout.confirm.message': 'Tem certeza de que deseja sair?',
    'profile.logout.confirm.cancel': 'Cancelar',
    'profile.logout.confirm.logout': 'Sair',

    // Subscription Screen
    'subscription.title': 'Tokens do Confluency',
    'subscription.current': 'Assinatura Atual',
    'subscription.plan': 'Plano',
    'subscription.usage': 'Uso de Tokens do Confluency',
    'subscription.reset': 'Reinicia em',
    'subscription.available.plans': 'Planos Disponíveis',
    'subscription.restore': 'Restaurar Compras',
    'subscription.expo.notice': 'Executando em modo de desenvolvimento. As compras são simuladas e não são cobradas.',
    'subscription.legal.text': 'As assinaturas serão renovadas automaticamente, a menos que a renovação automática seja desativada pelo menos 24 horas antes do final do período atual.',
    'subscription.manage.text': 'Você pode gerenciar suas assinaturas nas configurações da sua conta App Store/Google Play após a compra.',
    
    // Language Selection
    'language.i.speak': 'Eu falo:',
    'language.want.to.learn': 'Quero aprender:',
    'language.difficulty': 'Dificuldade:',
    'language.conversation.mode': 'Modo de Conversa:',
    'language.learning.objective': 'Objetivo de Aprendizado (opcional):',
    'language.start.button': 'Começar a Aprender',
    'language.app.title': 'Idioma do App',

    // Conversation Mode Translations
    'conversation.categories.conversations': 'Conversas',
    'conversation.categories.languageLessons': 'Aulas de Idioma',
    'conversation.freeConversation.label': 'Conversa Livre',
    'conversation.freeConversation.description': 'Participe de conversas naturais e não estruturadas sobre qualquer tópico que lhe interesse.',
    'conversation.freeConversation.placeholder': '• Game of Thrones\n• Dicas de Golf\n• Destinos de Férias',
    'conversation.topicLesson.label': 'Lição de Tópico Especial',
    'conversation.topicLesson.description': 'Explore tópicos fascinantes em seu idioma de destino - história, cultura, esporte, geopolítica...',
    'conversation.topicLesson.placeholder': '• História de Roma\n• Dicas de Treinamento para Cães\n• Movimentos de Arte Moderna',
    'conversation.interview.label': 'Entrevista',
    'conversation.interview.description': 'Expresse-se naturalmente enquanto responde perguntas sobre seus interesses, experiências e opiniões.',
    'conversation.interview.placeholder': '• Seus Hobbies\n• Experiências de Viagem\n• Objetivos de Vida',
    'conversation.situationSimulation.label': 'Simulação de Situação',
    'conversation.situationSimulation.description': 'Pratique conversas da vida real em cenários comuns como restaurantes, viagens e compras.',
    'conversation.situationSimulation.placeholder': '• Em um restaurante\n• Entrevista de emprego\n• Check-in no aeroporto\n• Comprando roupas',
    'conversation.verbChallenge.label': 'Desafio de Verbos',
    'conversation.verbChallenge.description': 'Pratique a construção de frases com verbos essenciais em diferentes tempos e modos.',
    'conversation.verbChallenge.placeholder': '• Tempos verbais específicos para praticar\n• Preferências de nível de dificuldade\n• Tipos de verbos',
    'conversation.verbChallenge.comingSoon': 'Em Breve',
    'conversation.topicTheme.label': 'Tópico/Tema',
    'conversation.generateRandomTopic': 'Gerar Tópico Aleatório',
    'conversation.selectMode': 'Selecionar Modo de Conversa',
    'conversation.topicInfo': 'O Confluency pode conversar com você sobre qualquer tópico que você possa imaginar - desde conselhos sobre relacionamentos até dança, do Antigo Egito à Taylor Swift!',
    'loading.generating': 'Gerando...',

    // Email Verification
    'email.verification.title': 'Verificação de Email Necessária',
    'email.verification.message': 'Seu endereço de email precisa ser verificado antes de continuar. Verifique sua caixa de entrada (incluindo pasta de spam) para um email de verificação, ou use o botão "Reenviar Email" abaixo.',
    'email.verification.ok': 'OK',
    'email.verification.resendEmail': 'Reenviar Email',
    'email.verification.checkingVerification': 'Verificando verificação...',
    'email.verification.emailSent': 'Email Enviado',
    'email.verification.emailSentMessage': 'Um novo email de verificação foi enviado. Verifique sua caixa de entrada.',
    'email.verification.errorSending': 'Erro ao Enviar',
    'email.verification.errorSendingMessage': 'Falha ao enviar email de verificação. Tente novamente.',
    'email.verification.verificationComplete': 'Verificação Completa',
    'email.verification.verificationCompleteMessage': 'Seu email foi verificado com sucesso.',
    'email.verification.networkError': 'Erro de Conexão',
    'email.verification.networkErrorMessage': 'Verifique sua conexão com a internet e tente novamente.',
    'email.verification.notVerified': 'Seu email ainda não foi verificado. Verifique sua caixa de entrada e clique no link de verificação.',
    'email.verification.checkEmail': 'Verifique seu email e clique no link de verificação para ativar sua conta.',
    'email.verification.checkEmailTitle': 'Verifique Seu Email',
    'email.verification.checkEmailMessage': 'Verifique sua caixa de entrada de email e clique no link de verificação para ativar sua conta. Após a verificação, você será automaticamente conectado.',
    'email.verification.cannotOpenEmail': 'Não é Possível Abrir Email',
    'email.verification.cannotOpenEmailMessage': 'Não foi possível abrir seu aplicativo de email. Verifique sua caixa de entrada de email manualmente.',
    'email.verification.verifyTitle': 'Verifique Seu Email',
    'email.verification.sentTo': 'Enviamos um email de verificação para:',
    'email.verification.instructions': 'Verifique sua caixa de entrada e clique no link de verificação para ativar sua conta. Não se esqueça de verificar sua pasta de spam ou lixo eletrônico.',
    'email.verification.offlineWarning': 'Você está offline. Conecte-se à internet para verificar seu email.',
    'email.verification.openEmailApp': 'Abrir App de Email',
    'email.verification.verifiedButton': 'Verifiquei Meu Email',
    'email.verification.helpText': 'Tendo problemas? Verifique sua pasta de spam ou entre em contato com nossa equipe de suporte para assistência.',

    // Quota Exceeded Modal
    'quota.exceeded.title': 'Limite de Tokens Atingido',
    'quota.exceeded.message': 'Você atingiu seu limite mensal de tokens para aprendizado de idiomas. Atualize sua assinatura para continuar aprendendo sem limites.',
    'quota.exceeded.upgradeNow': 'Atualizar Agora',
    'quota.exceeded.notNow': 'Agora Não',

    // Loading States
    'loading.general': 'Carregando...',
    'loading.savingPreferences': 'Salvando preferências...',
    'loading.connecting': 'Conectando...',
    'loading.verifying': 'Verificando...',
    'loading.sendingEmail': 'Enviando email...',

    // Status Messages
    'status.offline': 'Offline',
    'status.connecting': 'Conectando...',
    'status.connected': 'Conectado',
    'status.disconnected': 'Desconectado',

    // Error Messages
    'error.network.title': 'Erro de Conexão',
    'error.network.message': 'Não foi possível conectar ao servidor. Verifique sua conexão com a internet.',
    'error.auth.generic': 'Erro de autenticação. Tente novamente.',
    'error.auth.network': 'Erro de rede durante a autenticação.',
    'error.subscription.failed': 'Falha no processamento da assinatura.',
    'error.verification.failed': 'Falha na verificação de email.',

    // Placeholders
    'placeholder.learningObjective': 'ex. história romana, cultura japonesa...',
    'placeholder.searchLanguages': 'Pesquisar idiomas...',
    'placeholder.email': 'seu@email.com',
    'placeholder.password': 'Senha',

    // Accessibility Labels
    'accessibility.closeModal': 'Fechar modal',
    'accessibility.selectLanguage': 'Selecionar idioma',
    'accessibility.backButton': 'Botão voltar',
    'accessibility.menuButton': 'Botão menu',

    // Additional Button Labels
    'button.upgradeNow': 'Atualizar Agora',
    'button.notNow': 'Agora Não',
    'button.resendEmail': 'Reenviar Email',
    'button.tryAgain': 'Tentar Novamente',
    'button.ok': 'OK',

    // Common
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.warning': 'Aviso',
    'common.info': 'Info',
    
    // Buttons
    'button.cancel': 'Cancelar',
    'button.save': 'Salvar',
    'button.select': 'Selecionar',
    'button.continue': 'Continuar',
    'button.back': 'Voltar',
  },
};

// Provider component
export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [appLanguage, setAppLanguageState] = useState<string>(DEFAULT_LANGUAGE);

  // Load saved language on mount
  useEffect(() => {
    const loadSavedLanguage = async () => {
      try {
        const savedLanguage = await AsyncStorage.getItem(APP_LANGUAGE_KEY);
        if (savedLanguage) {
          setAppLanguageState(savedLanguage);
        }
      } catch (error) {
        console.error('Error loading saved app language:', error);
      }
    };

    loadSavedLanguage();
  }, []);

  // Function to set app language
  const setAppLanguage = async (code: string) => {
    try {
      await AsyncStorage.setItem(APP_LANGUAGE_KEY, code);
      setAppLanguageState(code);
    } catch (error) {
      console.error('Error saving app language:', error);
    }
  };

  // Function to translate keys based on current language
  const translate = (key: string): string => {
    // First check if the translation exists for current language
    if (translations[appLanguage] && translations[appLanguage][key]) {
      return translations[appLanguage][key];
    }
    
    // Fallback to English
    if (translations.en && translations.en[key]) {
      return translations.en[key];
    }
    
    // If no translation found, return the key itself
    return key;
  };

  // Function to get language name from code
  const getLanguageName = (code: string): string => {
    const language = LANGUAGES.find(lang => lang.code === code);
    return language ? language.name : code;
  };

  return (
    <LanguageContext.Provider value={{ appLanguage, setAppLanguage, translate, getLanguageName }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the language context
export const useLanguage = () => useContext(LanguageContext);

export default LanguageContext;